name: BrowserAutomationTest

on: [push]

jobs:
  Tests_PS5:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    strategy:
      matrix:
        browser: [Chrome, Firefox, EdgeChromium]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install Pester
        run: Install-Module Pester -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck

      - name: Collect environment
        run: |
          $PSVersionTable
          Get-ChildItem 'env:' | Format-Table -AutoSize -Wrap
          Get-Module -ListAvailable

      - name: Tests - ${{ matrix.browser }}
        run: Invoke-Pester -CI -Output Detailed
        env:
          TARGET_BROWSER: ${{ matrix.browser }}


  Tests_PS7:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    strategy:
      matrix:
        browser: [Chrome, Firefox, EdgeChromium]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install Pester
        run: Install-Module Pester -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck

      - name: Collect environment
        run: |
          $PSVersionTable
          Get-ChildItem 'env:' | Format-Table -AutoSize -Wrap
          Get-Module -ListAvailable

      - name: Tests - ${{ matrix.browser }}
        run: Invoke-Pester -CI -Output Detailed
        env:
          TARGET_BROWSER: ${{ matrix.browser }}
