name: BrowserAutomationTest

on: [push]

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        browser: [chrome, firefox]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Install Pester
      run: Install-Module Pester -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck
      shell: powershell

    - name: Add GeckDriver to the PATH
      if: contains(matrix.browser, 'Firefox')
      run: echo "##[add-path]$env:GeckoWebDriver"

    - name: Collect environment
      run: |
        $PSVersionTable
        Get-ChildItem 'env:' | Format-Table -AutoSize -Wrap
        Get-Module -ListAvailable
      shell: powershell

    - name: Tests - ${{ matrix.browser }}
      run: Invoke-Pester -EnableExit
      env:
        TARGET_BROWSER: ${{ matrix.browser }}
      shell: powershell
